//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercer.Tpa.Agenda.Web.UI.Admin {
    
    
    public partial class AdminAgendaInicio {
        
        /// <summary>
        /// ctrMensaje control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mercer.Tpa.Agenda.Web.UI.Utils.UserControlMessage ctrMensaje;
        
        /// <summary>
        /// ctrError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mercer.Tpa.Agenda.Web.UI.Utils.ControlMensajeError ctrError;
        
        /// <summary>
        /// txtHorasLimite control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtHorasLimite;
        
        /// <summary>
        /// btnGuardarParametros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnGuardarParametros;
    }
}
